name: CI CD

on:
    push: 
        branches: [ "main" ]
    pull_request:
        branches: [ "main" ]
    workflow_dispatch:
    
jobs:
    build:
        runs-on: ubuntu-latest
        strategy:
            matrix:
                python_version: ['3.7', '3.8', '3.9', '3.10', '3.11']

        steps: 
            - name: checkout code
              uses: actions/checkout@v3

            - name: set up Python ${{ matrix.python_version }}
              uses: actions/setup-python@v4
              with:
                python-version: ${{ matrix.python_version }}

            - name: install packages
              run: make install
            
            - name: format
              run: make format
            
            - name: lint
              run: make lint

            - name: test
              run: make test

